name: revit
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py39hf88036b_3
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cffi=1.17.1=py39h15c3d72_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.14=py39hf88036b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libzlib=1.2.13=h4ab18f5_6
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - protobuf=5.28.3=py39hf88036b_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic-core=2.33.2=py39h20260ba_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=7_cp39
  - pyzmq=26.4.0=py39h4e4fb57_0
  - readline=8.2=h8c095d6_2
  - sentry-sdk=2.35.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py39h8cd3c5a_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.5.1=py39h8cd3c5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - wandb=0.21.1=py39h2f71287_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py39hd399759_3
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - alembic==1.16.5
      - antlr4-python3-runtime==4.8
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==3.3.11
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.2.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - black==25.1.0
      - bleach==6.2.0
      - blessed==1.21.0
      - cachetools==6.0.0
      - captum==0.8.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cmake==4.0.2
      - colorlog==6.10.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==1.18.3
      - defusedxml==0.7.1
      - dill==0.4.0
      - distro==1.9.0
      - einops==0.4.0
      - fairscale==0.4.13
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.58.2
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gpustat==1.1
      - graphviz==0.21
      - greenlet==3.2.4
      - h11==0.16.0
      - hf-xet==1.1.3
      - higher==0.2.1
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.32.6
      - hydra-core==1.1.1
      - importlib-metadata==6.3.0
      - importlib-resources==6.5.2
      - inseq==0.6.0
      - iopath==0.1.10
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isort==6.0.1
      - jaxtyping==0.2.36
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lark==1.2.2
      - lit==18.1.8
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - nltk==3.6.5
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.1.1
      - openai==1.57.0
      - opencv-python==4.8.0.76
      - optuna==4.5.0
      - overrides==7.7.0
      - pandas==1.4.0
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - peft==0.7.1
      - pillow==11.2.1
      - pip==25.3
      - plantuml==0.3.0
      - portalocker==3.1.1
      - prometheus-client==0.22.1
      - propcache==0.3.2
      - pyarrow==20.0.0
      - pydantic==2.11.5
      - pyjwt==2.8.0
      - pylint==3.3.8
      - pyparsing==3.2.3
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyyaml==6.0
      - qwen-vl-utils==0.0.10
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - revit==0.1.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.26.0
      - ruff==0.14.9
      - safetensors==0.5.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tensorly==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timm==0.9.7
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchvision==0.15.2
      - transformers==4.46.2
      - triton==3.4.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20250708
      - uri-template==1.3.0
      - urllib3==2.4.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.20.1
      - zhipuai==2.1.5.20250410
